name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17-alpine
        env:
          POSTGRES_DB: planning_poker
          POSTGRES_USER: poker
          POSTGRES_PASSWORD: poker
        ports: [5432:5432]
        options: >-
          --health-cmd "pg_isready -U poker" --health-interval 5s --health-timeout 5s --health-retries 5
      redis:
        image: redis:7-alpine
        ports: [6379:6379]
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1  # bun for fast install but Node 22 is runtime
      - run: bun install
      - run: bun run prisma generate --workspace=server
      - run: bun run db:seed --workspace=server
      - run: bun test --workspace=server
      - run: bun run build --workspace=client
      - name: Playwright
        uses: microsoft/playwright-github-action@v1
        with:
          run-tests: true